spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: none  


multitenancy:   
  mtapp: 
    dataSources: 
      -
        tenantId: tenant_1 
        url: jdbc:mysql://authframework.cbuatu53m418.ap-southeast-1.rds.amazonaws.com:3306/dbtenant1?useSSL=false 
        username: TMUser 
        password: Tech49Must42 
        driverClassName: com.mysql.cj.jdbc.Driver 
      -
        tenantId: tenant_2
        url: jdbc:mysql://authframework.cbuatu53m418.ap-southeast-1.rds.amazonaws.com:3306/dbtenant2?useSSL=false
        username: TMUser
        password: Tech49Must42
        driverClassName: com.mysql.cj.jdbc.Driver        